### ISSUE TITLE
When will make 0.0.3 available on RubyGems.org?

### ISSUE THREAD

**Issue by mosuka** [yuuzi41/fluent-plugin-swift#4]
The pull request (# 3) seems to be resolved. When will make 0.0.3 available on RubyGems.org?
https://rubygems.org/gems/fluent-plugin-swift

**Comment by yuuzi41** [comment]
Sorry for a late releasing.
I've released 0.0.3 on RubyGems.org today.

**Comment by mosuka** [comment]
@yuuzi41 Thanks !
